<?php

/**
 * field_table_of_contents.module
 *
 * field_table_of_contents
 */

/**
 * Implements hook_theme().
 */
function field_table_of_contents_theme($existing,$type,$theme,$path) {
  return [
    'field_table_of_contents_field' => [
      'variables' => [
        'title' => '',
        'contents' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_node().
 */
function field_table_of_contents_preprocess_node(&$variables) {
  $generator = Drupal::service('field_table_of_contents.generator');

  $node = $variables['node'];
  $toc = $generator->lookup($node);

  if ($toc) {
    $toc->preprocessEntity($variables,$node);
  }
}

/**
 * Implements hook_preprocess_paragraph().
 */
function field_table_of_contents_preprocess_paragraph(&$variables) {
  $generator = Drupal::service('field_table_of_contents.generator');

  $paragraph = $variables['paragraph'];
  $toc = $generator->lookup($paragraph);

  if ($toc) {
    $toc->preprocessEntity($variables,$paragraph);
  }
}

/**
 * Local Variables:
 * mode:php
 * End:
 */
